### ISSUE TITLE
Hacer el procesamiento del video en diferido con la grabación.

### ISSUE THREAD

**Issue by facundoq** [midusi/sign-language-app#12]
Terminar de grabar, almacenando el video.

Luego reconocer los keypoints, y hacer la traducción (usar otro modal de "Traduciendo a Español...")

Luego mostrar traducción y video en loop como antes.

**Comment by indirivacua** [comment]
Esto lo estuve trabajando el fin de semana y llegué a la conclusión que no mejoraría la performance (incluso llega a empeorarla). TensorFlow.js tiene un [ejemplo](https://github.com/tensorflow/tfjs-models/tree/master/hand-pose-detection/demos/upload_video/src) de cómo laburar esto con un video que uno sube (acá sería lo mismo, solo que después de grabar se crea el objeto con los blobs guardados y se procesa de la misma manera, cosa que ya está hecho). 

Qué es lo que hay que hacer y por qué es tan lerdo: el ejemplo muestra que se le da play al video subido (_grabado_ 2*) sobre un tag HTML oculto, se dibuja el frame (1*) del video sobre un canvas, hace la inferencia y esta la dibuja sobre el mismo canvas (_debug=True_ 2*), en el mientras tanto *se va grabando el canvas y se van almacenando los chunks de este*. O sea, literalmente está haciendo lo mismo que en tiempo real, pero después, usando más procesamiento (ya que se graba dos veces y encima se tiene que dibujar el canvas completo siempre) y no mejorando siquiera el hecho de que sea compatible con más dispositivos (porque la cadena se sigue rompiendo por el eslabón más débil).

Aclaraciones:
1. (1*) El que agarre, no necesariamente procesa todos, depende de la capacidad del dispositivo (mismo problema que si se usa tiempo real).
2. (2*) Lo que está en itálica sería para nuestro caso

La pregunta termina siendo... sigue siendo factible hacerlo? Yo no tengo drama! Pero realmente luego de investigar y hacer las pruebas no le veo mucha utilidad.

**Comment by indirivacua** [comment]
Hablando ayer con @pedroodb llegamos a la conclusión de que no tiene sentido cambiar el modo de procesamiento.
