### ISSUE TITLE
Temporización para grabar y feedback

### ISSUE THREAD

**Issue by facundoq** [midusi/sign-language-app#4]
No se entiende/ve fácil cuánto tiempo queda para grabar

El contador de tiempo restante sería mejor que esté como overlay al video y más grande. Es imposible hacer una seña y ver cuánto tiempo te queda.

Además, Luego de los 3 segundos al principio debería mandar un mensaje tipo "Señá!"

**Comment by facundoq** [comment]
Luego de grabar, debería mostrar el video en loop (izquierda) y a la derecha el texto traducido.

Un botón de "Grabar de nuevo" o similar.

De hecho podemos pensar por default una interfaz tipo google translate con el panel de "input" a la izquierda (para grabar video) y de "output" a la derecha. Cuando terminás de grabar, mientras se corre el modelo de reconocimiento la parte de la derecha aparece como "cargando" y cuando termina se muestra el texto.

**Comment by indirivacua** [comment]
> No se entiende/ve fácil cuánto tiempo queda para grabar
> 
> El contador de tiempo restante sería mejor que esté como overlay al video y más grande. Es imposible hacer una seña y ver cuánto tiempo te queda.
> 
> Además, Luego de los 3 segundos al principio debería mandar un mensaje tipo "Señá!"

Esto lo tengo ready para pushear 🙌 

> Luego de grabar, debería mostrar el video en loop (izquierda) y a la derecha el texto traducido.
> 
> Un botón de "Grabar de nuevo" o similar.
> 
> De hecho podemos pensar por default una interfaz tipo google translate con el panel de "input" a la izquierda (para grabar video) y de "output" a la derecha. Cuando terminás de grabar, mientras se corre el modelo de reconocimiento la parte de la derecha aparece como "cargando" y cuando termina se muestra el texto.

Acá me perdí con la idea de interface, cuándo lo podemos charlar?

**Comment by facundoq** [comment]
El jue, 26 de may. de 2022 10:52, Oscar Stanchi ***@***.***>
escribió:

> No se entiende/ve fácil cuánto tiempo queda para grabar
>
> El contador de tiempo restante sería mejor que esté como overlay al video
> y más grande. Es imposible hacer una seña y ver cuánto tiempo te queda.
>
> Además, Luego de los 3 segundos al principio debería mandar un mensaje
> tipo "Señá!"
>
> Esto lo tengo ready para pushear 🙌
>
> Luego de grabar, debería mostrar el video en loop (izquierda) y a la
> derecha el texto traducido.
>
> Un botón de "Grabar de nuevo" o similar.
>
> De hecho podemos pensar por default una interfaz tipo google translate con
> el panel de "input" a la izquierda (para grabar video) y de "output" a la
> derecha. Cuando terminás de grabar, mientras se corre el modelo de
> reconocimiento la parte de la derecha aparece como "cargando" y cuando
> termina se muestra el texto.
>
> Acá me perdí con la idea de interface, cuándo lo podemos charlar?
>
Digo que después de que te reconoce lo que decís no podés volver a ver el
video con los movimientos que hiciste. Estaría bueno que además de que te
muestre el texto también te muestre el video original reproduciéndose en
loop.

Mañana si vas un rato lo podemos conversar!

**Comment by indirivacua** [comment]
@facundoq Creo que ahí quedó, te dejo el [video](https://www.youtube.com/watch?v=_7CmdglToZo) a ver si capté la idea correctamente 😉 (pd: iba a ir, pero por quedándome haciéndolo de manija que soy no fui al final :P).

**Comment by facundoq** [comment]
Espectacular! Y que bien anda el modelo, te reconoció las señas de "falló
la conexión con la API" :D
